### ISSUE TITLE
Can you update it 

### ISSUE THREAD

**Issue by DoctorWhoFR** [IAMRichardT/GmodScriptSkeleton#1]
Now gmod script skeleton don't work ;(

**Comment by im-richard** [comment]
I apologize for not seeing this; I moved away from the simple skeleton I wrote, and have just released rlib which is available in my repo, it's a complete lib to develop gmod addons with and is what I use now and will be using it for all my products. If you have issues with it, drop me an issues report over there, I check them now.

Documentation is coming as soon as I finish updating a few things to it.
